/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;


import com.jooqtest.model.tables.Author;
import com.jooqtest.model.tables.Book;
import com.jooqtest.model.tables.DinnerFavorites;
import com.jooqtest.model.tables.DinnerGuests;
import com.jooqtest.model.tables.Food;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooqtest extends SchemaImpl {

    private static final long serialVersionUID = 1419130730;

    /**
     * The reference instance of <code>jooqtest</code>
     */
    public static final Jooqtest JOOQTEST = new Jooqtest();

    /**
     * The table <code>jooqtest.author</code>.
     */
    public final Author AUTHOR = com.jooqtest.model.tables.Author.AUTHOR;

    /**
     * The table <code>jooqtest.book</code>.
     */
    public final Book BOOK = com.jooqtest.model.tables.Book.BOOK;

    /**
     * The table <code>jooqtest.dinner_favorites</code>.
     */
    public final DinnerFavorites DINNER_FAVORITES = com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES;

    /**
     * The table <code>jooqtest.dinner_guests</code>.
     */
    public final DinnerGuests DINNER_GUESTS = com.jooqtest.model.tables.DinnerGuests.DINNER_GUESTS;

    /**
     * The table <code>jooqtest.food</code>.
     */
    public final Food FOOD = com.jooqtest.model.tables.Food.FOOD;

    /**
     * No further instances allowed
     */
    private Jooqtest() {
        super("jooqtest", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            DinnerFavorites.DINNER_FAVORITES,
            DinnerGuests.DINNER_GUESTS,
            Food.FOOD);
    }
}
