/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;


import com.jooqtest.model.tables.Author;
import com.jooqtest.model.tables.Book;
import com.jooqtest.model.tables.DinnerFavorites;
import com.jooqtest.model.tables.DinnerGuests;
import com.jooqtest.model.tables.Food;
import com.jooqtest.model.tables.records.AuthorRecord;
import com.jooqtest.model.tables.records.BookRecord;
import com.jooqtest.model.tables.records.DinnerFavoritesRecord;
import com.jooqtest.model.tables.records.DinnerGuestsRecord;
import com.jooqtest.model.tables.records.FoodRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>jooqtest</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = UniqueKeys0.KEY_AUTHOR_PRIMARY;
    public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = UniqueKeys0.KEY_BOOK_PRIMARY;
    public static final UniqueKey<DinnerGuestsRecord> KEY_DINNER_GUESTS_PRIMARY = UniqueKeys0.KEY_DINNER_GUESTS_PRIMARY;
    public static final UniqueKey<FoodRecord> KEY_FOOD_PRIMARY = UniqueKeys0.KEY_FOOD_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DinnerFavoritesRecord, FoodRecord> DINNER_FAVORITES_IBFK_1 = ForeignKeys0.DINNER_FAVORITES_IBFK_1;
    public static final ForeignKey<DinnerFavoritesRecord, DinnerGuestsRecord> DINNER_FAVORITES_IBFK_2 = ForeignKeys0.DINNER_FAVORITES_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthorRecord> KEY_AUTHOR_PRIMARY = createUniqueKey(Author.AUTHOR, "KEY_author_PRIMARY", Author.AUTHOR.AUTHOR_ID);
        public static final UniqueKey<BookRecord> KEY_BOOK_PRIMARY = createUniqueKey(Book.BOOK, "KEY_book_PRIMARY", Book.BOOK.BOOK_ID);
        public static final UniqueKey<DinnerGuestsRecord> KEY_DINNER_GUESTS_PRIMARY = createUniqueKey(DinnerGuests.DINNER_GUESTS, "KEY_dinner_guests_PRIMARY", DinnerGuests.DINNER_GUESTS.ID);
        public static final UniqueKey<FoodRecord> KEY_FOOD_PRIMARY = createUniqueKey(Food.FOOD, "KEY_food_PRIMARY", Food.FOOD.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<DinnerFavoritesRecord, FoodRecord> DINNER_FAVORITES_IBFK_1 = createForeignKey(com.jooqtest.model.Keys.KEY_FOOD_PRIMARY, DinnerFavorites.DINNER_FAVORITES, "dinner_favorites_ibfk_1", DinnerFavorites.DINNER_FAVORITES.FOODID);
        public static final ForeignKey<DinnerFavoritesRecord, DinnerGuestsRecord> DINNER_FAVORITES_IBFK_2 = createForeignKey(com.jooqtest.model.Keys.KEY_DINNER_GUESTS_PRIMARY, DinnerFavorites.DINNER_FAVORITES, "dinner_favorites_ibfk_2", DinnerFavorites.DINNER_FAVORITES.DINNER_GUEST_ID);
    }
}
