/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;


import com.jooqtest.model.tables.Author;
import com.jooqtest.model.tables.Book;
import com.jooqtest.model.tables.DinnerFavorites;
import com.jooqtest.model.tables.DinnerGuests;
import com.jooqtest.model.tables.Food;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqtest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtest.author</code>.
     */
    public static final Author AUTHOR = com.jooqtest.model.tables.Author.AUTHOR;

    /**
     * The table <code>jooqtest.book</code>.
     */
    public static final Book BOOK = com.jooqtest.model.tables.Book.BOOK;

    /**
     * The table <code>jooqtest.dinner_favorites</code>.
     */
    public static final DinnerFavorites DINNER_FAVORITES = com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES;

    /**
     * The table <code>jooqtest.dinner_guests</code>.
     */
    public static final DinnerGuests DINNER_GUESTS = com.jooqtest.model.tables.DinnerGuests.DINNER_GUESTS;

    /**
     * The table <code>jooqtest.food</code>.
     */
    public static final Food FOOD = com.jooqtest.model.tables.Food.FOOD;
}
