/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables.records;


import com.jooqtest.model.tables.DinnerFavorites;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DinnerFavoritesRecord extends TableRecordImpl<DinnerFavoritesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1572611610;

    /**
     * Setter for <code>jooqtest.dinner_favorites.foodid</code>.
     */
    public void setFoodid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooqtest.dinner_favorites.foodid</code>.
     */
    public Long getFoodid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooqtest.dinner_favorites.dinner_guest_id</code>.
     */
    public void setDinnerGuestId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooqtest.dinner_favorites.dinner_guest_id</code>.
     */
    public Long getDinnerGuestId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DinnerFavorites.DINNER_FAVORITES.FOODID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return DinnerFavorites.DINNER_FAVORITES.DINNER_GUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getFoodid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getDinnerGuestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DinnerFavoritesRecord value1(Long value) {
        setFoodid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DinnerFavoritesRecord value2(Long value) {
        setDinnerGuestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DinnerFavoritesRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DinnerFavoritesRecord
     */
    public DinnerFavoritesRecord() {
        super(DinnerFavorites.DINNER_FAVORITES);
    }

    /**
     * Create a detached, initialised DinnerFavoritesRecord
     */
    public DinnerFavoritesRecord(Long foodid, Long dinnerGuestId) {
        super(DinnerFavorites.DINNER_FAVORITES);

        set(0, foodid);
        set(1, dinnerGuestId);
    }
}
